### ISSUE TITLE
Links to openqa.org and release.seleniumhq.org are all broken

### ISSUE THREAD

**Issue by fenwar** [SeleniumHQ/www.seleniumhq.org#106]
It looks like openqa.org has gone away. In particular the following link (command reference for Selenium IDE):

http://release.seleniumhq.org/selenium-core/1.0/reference.html

(In the code here: https://github.com/SeleniumHQ/www.seleniumhq.org/blame/master/src/main/rst/02_selenium_ide.rst#L433 )

I'd submit a PR but I don't know where this content has actually moved to :(

**Comment by lukeis** [comment]
@lightbody is openqa.org gone forever now?

**Comment by fenwar** [comment]
for the benefit of anyone trying to track the Selenium IDE command reference down, the HTML source can be found at:
https://github.com/SeleniumHQ/selenium/blob/master/ide/main/src/content/selenium-core/reference.html

**Comment by diemol** [comment]
Hi @fenwar,

Can you please have a look at the new [docs](https://selenium.dev/documentation/en/) and new [site](https://selenium.dev/), and in case you still find the issue, please create an issue at https://github.com/SeleniumHQ/seleniumhq.github.io.
