### ISSUE TITLE
Reference document link is not working.

### ISSUE THREAD

**Issue by sachansoft** [SeleniumHQ/www.seleniumhq.org#107]
Steps to Repro:

1. Launch the URL: http://www.seleniumhq.org/docs/02_selenium_ide.jsp
2. Go under Reference Pane
3. Read the last line of this pane
4. Their is a link **Reference**
![seleniumide](https://cloud.githubusercontent.com/assets/20810246/18540854/2c04b8b0-7b3f-11e6-9d6f-9a5e97a2ea50.png)
5. Click on this link and observe that it is not working
![refdoc](https://cloud.githubusercontent.com/assets/20810246/18540879/4df087ba-7b3f-11e6-9115-ff33de7deb4e.png)

**Comment by manoj9788** [comment]
Known Issue #106

**Comment by lukeis** [comment]
closing as a duplicate
