### ISSUE TITLE
sendKeys() doesn't  enter number 5 ,6 in Ubuntu

### ISSUE THREAD

**Issue by hima65** [SeleniumHQ/www.seleniumhq.org#108]
Hi There,

While running the tests in selenium grid in Ubuntu(16.04) platform , am facing an issue where sendKeys doesn't enter number 5 & 6 even though it is passed as a number or a string to the input fields. Please let me know if there is anyone facing the same issue. 
 
Platform: Ubuntu 16.04
ChromeDriver: 2.24
Selenium-standalone-Version : 2.52.0
Chrome version : 52.x

Thanks,
Sri Harsha.

**Comment by lukeis** [comment]
please log selenium related problems with the SeleniumHQ/selenium repo instead. This repo is just for the documentation website.

Alos be sure to include a reproducible test script and include a link to a page to reproduce or recreate the page in question using jsfiddle.net

Additionally, chromedriver issues should be logged with the chromedriver project:
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by lukeis** [comment]
There's also a google group to ask questions / seek guidance:

https://groups.google.com/forum/#!forum/selenium-users
