### ISSUE TITLE
Selenium version on site is 3.0.1, but it has the changelog for 3.0.2 release

### ISSUE THREAD

**Issue by g-tiwari** [SeleniumHQ/www.seleniumhq.org#120]
When i click on [Change-log](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG) link of JAVA binding for Selenium, It also shows me change-log for version 3.0.2. But its officials version is 3.0.1

Is it a mistake or version 3.0.2 version is yet to be published?

Thanks
Gaurav Tiwari

**Comment by lukeis** [comment]
We were just getting it ready for a release, which I intended to do last week but ran short on spare time. I'll likely get to it this week
