### ISSUE TITLE
Firefox hangs longtime/forever in page loading state during execution of selenium tests

### ISSUE THREAD

**Issue by rajimitara** [SeleniumHQ/www.seleniumhq.org#128]
I have couple of selenium test code written in Java (run from cucumber), When I ran the test in jenkins using the firefox 45.0.1 the build gets through several tests and browser just hangs/stuck forever without timeout. It is widely reproducible in Jenkins and firefox hangs at random pages of a application during execution of testcase. Apparently there are no client-server comm problem and the firefox client has received the response and hangs internally before rendering the response.(We have no clues why firefox stays there longtime/forever as log, jstack, ps, server health has no weird behavior).

Issue persists even after changing selenium & firefox versions to avoid compatibility issues.

Jenkins version : 1.629
Selenium version: 2.53.1
OS: Cent-OS 6.5
Browser: Firefox 
Browser version: 45.0.1

**Comment by sureshkumar-skc** [comment]
It is happenings for me also sometimes. The test case just stuck and it will not throws any exception also.
I tried to reproduce but no success.

**Comment by rajimitara** [comment]
@sureshkumar-skc Could you please mention your firefox,selenium & jenkins versions you are using.
Any luck with firefox logs?

**Comment by vishnupriya1987** [comment]
I face the same kind of issue.. After a specific number of tests,Internet Explorer browser freezes for infinite time with no error or exception thrown.
I am using Selenium 3.0 with IE11 in Windows 10. Also I am using TestNG with Java for my project.
Same issue happens with Firefox too....

**Comment by sureshkumar-skc** [comment]
@rajimitara the versions were

OS: Windows 10 x64

Selenium Version: 3.0.1

Browser: firefox

Browser Version: 50.1.0 (64-bit)

**Comment by lmtierney** [comment]
This is the repo for the seleniumhq.org website, not the webdriver repo. Also, this is a question rather than an issue. Please read [Bug Reporting](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) and either raise an issue with a reproducible test case or seek help from the mailing list
