### ISSUE TITLE
Bad gateway (502) when trying to access http://release.seleniumhq.org/selenium-core/1.0.1/reference.html

### ISSUE THREAD

**Issue by dwbrant** [SeleniumHQ/www.seleniumhq.org#129]
I've been trying to access the link for the past three or four days. Down for everyone reports that it is down for .. everyone, of course.

Bad gateway (502) when trying to access http://release.seleniumhq.org/selenium-core/1.0.1/reference.html

**Comment by dwbrant** [comment]
The link referenced above was found on:

http://www.seleniumhq.org/docs/02_selenium_ide.jsp#selenium-commands-selenese

"Command Reference"

**Comment by fenwar** [comment]
for the benefit of anyone trying to track the Selenium IDE command reference down, the HTML source can be found at:
https://github.com/SeleniumHQ/selenium/blob/master/ide/main/src/content/selenium-core/reference.html

**Comment by diemol** [comment]
Hi @dwbrant,

Can you please have a look at the new [docs](https://selenium.dev/documentation/en/) and new [site](https://selenium.dev/), and in case you still find the issue, please create an issue at https://github.com/SeleniumHQ/seleniumhq.github.io.
