### ISSUE TITLE
FluentWait<T> should support wait.while(isTrue) semantics

### ISSUE THREAD

**Issue by Martin-Spamer** [SeleniumHQ/www.seleniumhq.org#133]
Currently FluentWait provides _wait until_ semantics, e.g.
`wait.until(isTrue)`

This can lead to double negative conditions which reduces clarity and increases complexity.  

The could be readily improved with _wait while_ semantics, e.g.

` wait.while(isTrue)`

**Comment by ddavison** [comment]
not exactly sure this belongs here.  are you asking to update the site somewhere? or is this a feature request that belongs in https://github.com/seleniumhq/selenium/issues  ?

**Comment by Martin-Spamer** [comment]
Yes, sorry wrong repo.
