### ISSUE TITLE
No javadoc or source jars on maven repo

### ISSUE THREAD

**Issue by timrsfo** [SeleniumHQ/www.seleniumhq.org#143]
Could you please post the javadoc and javasrc jars to maven for versions after 2.44?

**Comment by lukeis** [comment]
They are published, for example the selenium-server module

http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-server/3.3.1/

**Comment by timrsfo** [comment]
http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.47.0/
take a look at selenium-java between 2.44.0 and 2.60.0, some have src, some have javadoc, most have neither

**Comment by timrsfo** [comment]
https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/2.53.1 is the last 2.xx version in the maven repo prior to the jump to 3.xx. 
see: http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.53.1/

**Comment by lukeis** [comment]
yes... the jar is actually empty, there's no class files in it. We switched to using Buck to generate the artifacts and essentially it's a bug in Buck that it's generating the jar at all, could just be a pom file.

But there's nothing technically wrong with having an empty jar file, maven handles it just fine. The java classes live in other packages.

**Comment by timrsfo** [comment]
not sure what you mean by - the jar is actually empty

let me explain my issue, I'm using Eclipse IDE. Trying to download src/javadoc for included maven jars. since I'm now using the latest greatest 2.xx version, 2.53.1 which has neither scr nor javadoc published I lose functionality. 

Do you have any suggestions?
thanks

**Comment by lukeis** [comment]
"selenium-java" is not the only maven artifact. There's many more that are listed in its dependencies... those actually have the src / javadoc you are looking for. You aren't adequately describing the problem you're experiencing for me to help further. I'd suggest following up on the selenium-users mailing list before attempting to raise an bug here.

https://groups.google.com/forum/#!forum/selenium-users
