### ISSUE TITLE
seems like your target & value fields are reversed here (docs):

### ISSUE THREAD

**Issue by jterry999** [SeleniumHQ/www.seleniumhq.org#15]
Store Commands and Selenium Variables

You can use Selenium variables to store constants at the beginning of a script. Also, when combined with a data-driven test design (discussed in a later section), Selenium variables can be used to store values passed to your test program from the command-line, from another program, or from a file.

The plain store command is the most basic of the many store commands and can be used to simply store a constant value in a selenium variable. It takes two parameters, the text value to be stored and a selenium variable. Use the standard variable naming conventions of only alphanumeric characters when choosing a name for your variable.
Command 	Target 	Value
store 	paul@mysite.org 	userName

**Comment by lukeis** [comment]
What page and section(s) are you talking about?

You could provide a pull request for the change you are taking about.

**Comment by samitbadle** [comment]
Thank you for pointing this out. While the command is not intuitive, the documentation is in fact correct. The first parameter to store is the value and the second parameter is the variable name. Changing the command to take the parameters in a more intuitive manner would break many scripts and cannot be done. I know that many people get confused by it and it is such a common error to get the order wrong that I wrote an inspector to automatically detect and fix this in my Selenium Expert plugin for Selenium IDE.
