### ISSUE TITLE
Could you please update document to 3.4.0 ?

### ISSUE THREAD

**Issue by xiaoCong2014** [SeleniumHQ/www.seleniumhq.org#153]
Could you update the official document to the latest version of Selenium (such as version 3.4.0, at least 3.x version)? The way of building local environment for Selenium 3.x is exactly the same as selenium 2? Are you sure ?

The older document whited at beginning --> "Note to the Reader - Docs Being Revised for Selenium 2.0! " not Selenium 3.x
document link : http://www.seleniumhq.org/docs/

OS:
Windows 10
Selenium Version:
3.4.0
Browser:
Chrome 54

**Comment by lmtierney** [comment]
The documents are undergoing an overhaul but it is slow going as there are few contributors. If you'd like to help out, head on over to https://github.com/seleniumhq/docs

The new docs site will be https://seleniumhq.github.io/docs
