### ISSUE TITLE
Javascript Example Doesn't Include require() statement

### ISSUE THREAD

**Issue by tobkin** [SeleniumHQ/www.seleniumhq.org#158]
Hi,

Editorial suggestion because it confused me:

On the [Selenium Webdriver page](http://docs.seleniumhq.org/docs/03_webdriver.jsp#chapter03-reference), the JavaScript example does not include the line `var webdriver = require('selenium-webdriver')`. The Java example does include imports. So the example does not run as-is.

Hope that helps! Pardon me if it's an oversight on my part!

**Comment by manoj9788** [comment]
@tobkin do you want to send in a PR for this change?

**Comment by tobkin** [comment]
@manoj9788 Oh that would be the more useful thing for me to do, wouldnt it lol? Yeah I'll figure out how your docs work and do that tomm morning.

**Comment by manoj9788** [comment]
on top of the page, there will be an "edit this page" button.

**Comment by diemol** [comment]
Hi @tobkin ,

Can you please have a look at the new [docs](https://selenium.dev/documentation/en/) and new [site](https://selenium.dev/), and in case you still find the issue, please create an issue at https://github.com/SeleniumHQ/seleniumhq.github.io.
