### ISSUE TITLE
Javascript example not working

### ISSUE THREAD

**Issue by macroking** [SeleniumHQ/www.seleniumhq.org#166]
http://www.seleniumhq.org/docs/03_webdriver.jsp
Example in section -  Introducing the Selenium-WebDriver API by Example 

Issues:
1. ReferenceError: webdriver is not defined. (fix: By adding a require statement)
2. TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser() ( fix : make a forBrowser('firefox') call)
3. Error: The geckodriver.exe executable could not be found on the current PATH. (Download and set the geckodriver path in the example)

**Comment by manoj9788** [comment]
Do you want raise a PR ?

**Comment by macroking** [comment]
I'm working on it.

**Comment by diemol** [comment]
Closing as the related PR was never merged and we have a new site and new docs as well.
Apologies again @macroking!
