### ISSUE TITLE
Can't add extension in headless chrome browser in selenium

### ISSUE THREAD

**Issue by KDsankar** [SeleniumHQ/www.seleniumhq.org#173]
If i try to add extension in my headless chrome the below exception is throwing

Caused by: org.openqa.selenium.WebDriverException: unknown error: failed to wait for extension background page to load: chrome-extension://bpjbgjeaagkflhjbbnjflonhepfoopdm/background.html
from unknown error: page could not be found: chrome-extension://bpjbgjeaagkflhjbbnjflonhepfoopdm/background.html

**Comment by lmtierney** [comment]
This repo is for the www.seleniumhq.org website. Issues for selenium should be added to the code repo https://github.com/seleniumhq/selenium/issues. That being said, it sounds like you just need to update your chromedriver to the latest.
