### ISSUE TITLE
FF version , selenium verion and geckodriver version compatibity

### ISSUE THREAD

**Issue by mehakaggarwal** [SeleniumHQ/www.seleniumhq.org#177]
Can anyone please help me which version of firefox starting from FF45 is compatible with which version of selenium and geckodriver.

**Comment by diemol** [comment]
@mehakaggarwal there is a doc that tries to clarify that https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
For older versions, I would recommend asking the community through the channels mentioned here https://selenium.dev/support/
