### ISSUE TITLE
Cosmetic issue on Selenium documentation

### ISSUE THREAD

**Issue by mmerrell** [SeleniumHQ/www.seleniumhq.org#196]
**Meta -**
OS: Any

Selenium Version: NA

Browser: All

Browser Version: Any

**Expected Behavior -**
word 'on' should be present between the words doc3861 and one .
word doc3861 should be in quotes because ‘doc6148’ is also in single quotes.
**Actual Behavior -**
word 'on' is missing between the words doc3861 and one
word doc3861 is not in quotes whereas word ‘doc6148’ is in single quotes.
**Steps to reproduce -**
Navigate to page/URL: https://www.seleniumhq.org/docs/06_test_design_considerations.jsp#introducing-test-design.
Move to section: 'Testing Dynamic Elements'

![image](https://user-images.githubusercontent.com/1610147/42973166-c91bab1e-8b77-11e8-9fe9-4527bd30895d.png)

**Comment by mmerrell** [comment]
Submitted a PR

**Comment by lukeis** [comment]
fixed with #198
