### ISSUE TITLE
SeleniumHQ website missing 3.14.0 update

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/www.seleniumhq.org#200]
@jsa34 commented on [Sat Aug 11 2018](https://github.com/SeleniumHQ/selenium/issues/6273)

I realise this is not a selenium functional issue, but the website is still pointing to 3.13.0 as the latest version, and would be great if it could be updated to 3.14.0 with release notes.

---

@lmtierney commented on [Mon Aug 13 2018](https://github.com/SeleniumHQ/selenium/issues/6273#issuecomment-412393876)

Issues like these should be raised with the website repo https://github.com/SeleniumHQ/www.seleniumhq.org/issues

**Comment by lmtierney** [comment]
Fixed in https://github.com/SeleniumHQ/www.seleniumhq.org/commit/ce67b9aa7d227a6e2813dad912fc22cbbdff9b85
