### ISSUE TITLE
Maven download page link redirects to main page.

### ISSUE THREAD

**Issue by Vvalter** [SeleniumHQ/www.seleniumhq.org#203]
The maven download page link on [webdriver documentation site](https://www.seleniumhq.org/docs/03_webdriver.jsp) redirects to the main page on my browser (Firefox 63.0).

I think the problem is that it is missing the www:
[http://seleniumhq.org/download/maven.html](http://seleniumhq.org/download/maven.html) redirects to main page, but [http://www.seleniumhq.org/download/maven.html](http://www.seleniumhq.org/download/maven.html) redirects to the maven page.

**Comment by Vimal-N** [comment]
@Vvalter - Change for Maven reference issue is submitted for review. Thanks!

**Comment by manoj9788** [comment]
Closed via 27d9f9f Thanks @Vimal-N
