### ISSUE TITLE
What is use of selenium-chrome-driver dependency, without chrome binary file?

### ISSUE THREAD

**Issue by ishah09** [SeleniumHQ/www.seleniumhq.org#204]
I did not found any official documentation on this, When this(selenium-chrome-driver) dependency can be use ? 

    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-chrome-driver</artifactId>
        <version>3.14.0</version>
    </dependency>

*On many answers I have read, It need to use with Chrome binary definition. By using only chrome binary we are able to execute script on Chrome Browser. Thus, driver calling is subject with Binary definition.*

**Question: So what is the use of this dependency, without chrome binary file ?** 

I have referred below answers and tried, without using binary declaration. Which says to use WebDriverManager dependency.

https://stackoverflow.com/questions/35867102/how-to-work-with-chrome-driver-in-maven

https://stackoverflow.com/questions/7450416/selenium-2-chrome-driver

https://stackoverflow.com/a/39809773/9405154

https://github.com/bonigarcia/webdrivermanager

**Comment by diemol** [comment]
Hi @ishah09,
 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
