### ISSUE TITLE
Minor - Section: Navigation Panel - right s/b left

### ISSUE THREAD

**Issue by newbie-ET** [SeleniumHQ/www.seleniumhq.org#213]
Wrong:
Navigation between test cases and test suites is done through the right hand side of Selenium IDE.
Right:
Navigation between test cases and test suites is done through the **left** hand side of Selenium IDE.

**Comment by diemol** [comment]
Please post Selenium IDE issues at https://github.com/SeleniumHQ/selenium-ide
