### ISSUE TITLE
The word "extensibily" does not exist. 

### ISSUE THREAD

**Issue by hsoJosh** [SeleniumHQ/www.seleniumhq.org#217]
The typo appears on this page: https://www.seleniumhq.org/docs/06_test_design_considerations.jsp

"We also describe ‘design patterns’ commonly used in test automation for improving the maintenance and extensibily of your automation suite"

I think the word that is supposed to be there is: extensibility

**Comment by diemol** [comment]
Would you like to send a PR anfd fix it?

**Comment by hsoJosh** [comment]
@diemol - I submitted an edit of the page.

**Comment by diemol** [comment]
Where? I don't see the pull request.

**Comment by diemol** [comment]
Closing as the OP didn't give us more information.
