### ISSUE TITLE
Documentation: Navigation not working from Table of content (left side in documentation)

### ISSUE THREAD

**Issue by PramodKumarYadav** [SeleniumHQ/www.seleniumhq.org#22]
Go to Documentation and click on some topic. 
Once inside a topic, try to navigate to another topic by clicking on a topic given under " Table of Contents ". 
Expected result: The page should get refreshed with the topic on top.
Actual result: No changes. PFA the screenshot.

**Comment by ddavison** [comment]
i'll investigate

**Comment by ddavison** [comment]
**Works** in firefox
**Fails** in chrome / safari / opera
