### ISSUE TITLE
Unable to locate the mailing list

### ISSUE THREAD

**Issue by noloader** [SeleniumHQ/www.seleniumhq.org#221]
A small usability issue... The Selenium HQ homepage is at https://www.seleniumhq.org/ . The webpage does not provide the location of the mailing list.

**Comment by lmtierney** [comment]
Moved here for disucssion

**Comment by diemol** [comment]
This did not get more traction and no one seemed interested in this. We have a new site, https://selenium.dev/support/, so in case we want to still discussing this, please raise an issue at https://github.com/SeleniumHQ/seleniumhq.github.io
