### ISSUE TITLE
Typo in 01_introducing_selenium: testing get done

### ISSUE THREAD

**Issue by odCat** [SeleniumHQ/www.seleniumhq.org#236]
The full sentence: 

> If an application has a very tight deadline, there is currently no test automation available, and it's imperative that the testing **get** done within that time frame, then manual testing is the best solution.

It should be "testing **gets** done".

Please let me know if you want me to make a PR.

**Comment by diemol** [comment]
Hi @odCat,
We are in the process of deprecating this repository. 
Please have a look at https://github.com/SeleniumHQ/seleniumhq.github.io and https://selenium.dev. If you still find the typo there, feel free to send us a PR..

**Comment by odCat** [comment]
The new site looks good. Thank you.
