### ISSUE TITLE
need updated / new quick start guides

### ISSUE THREAD

**Issue by lukeis** [SeleniumHQ/www.seleniumhq.org#24]
per language for client setup.

per browser for binding direct or standalone server. include mobile!

related issues:
https://github.com/SeleniumHQ/docs/issues/69
https://code.google.com/p/selenium/issues/detail?id=8327

**Comment by tarun3kumar** [comment]
>  include mobile!

Do we want to write mobile specific example codes as well?

**Comment by lukeis** [comment]
actually, i don't think I want that... we should point users to the mobile specific instructions (so, links to appium docs or selendroid docs or WebDriverAgent docs etc.)

**Comment by deepashreekm** [comment]
How do I contribute for the Doc?

**Comment by cgoldberg** [comment]
> How do I contribute for the Doc?

AFAIK, doc contributions here follow a similar process as contributions in the main Selenium repo.   You can submit a Pull Request here on GitHub.  The PR will be reviewed by Selenium committers.

**Comment by diemol** [comment]
We have a new site at https://github.com/SeleniumHQ/seleniumhq.github.io, this should be already solved, and in case it is not, please raise an issue there.
