### ISSUE TITLE
Deadlink in Documentation

### ISSUE THREAD

**Issue by ddavison** [SeleniumHQ/www.seleniumhq.org#40]
*migrated from https://github.com/SeleniumHQ/selenium/issues/1013*

@notnull1
http://docs.seleniumhq.org/docs/07_selenium_grid.jsp#what-is-selenium-grid
Chapter : How Selenium-Grid Works–With a Hub and Nodes¶
Deadlink at : "A diagram illustrates this."  to : http://selenium-grid.seleniumhq.org/how_it_works.html

**Comment by lukeis** [comment]
here's that original page:
https://code.google.com/p/selenium/source/browse/src/main/webapp/how_it_works.html?repo=grid

the 'grid' documentation site has been down for some time... but we can get the information if we need to, by looking at that repo

**Comment by ph-One** [comment]
:+1: still broken :disappointed:

**Comment by lukeis** [comment]
removed the link ;)
