### ISSUE TITLE
Update Browser Section

### ISSUE THREAD

**Issue by JoeSoccerFan** [SeleniumHQ/www.seleniumhq.org#69]
Hi - I'm a new Selenium user.

The browser section on this page is outdated.  It should have additional ie versions.
http://www.seleniumhq.org/docs/01_introducing_selenium.jsp

The top of the section is the following:

_Selenium

 1.0 and Selenium-RC.

This is the old, support platform for Selenium 1.0. It should still apply to the Selenium 2.0 release of Selenium-RC.__

**Comment by diemol** [comment]
Hi @JoeSoccerFan,

Can you please have a look at the new [docs](https://selenium.dev/documentation/en/) and new [site](https://selenium.dev/), and in case you still find the issue, please create an issue at https://github.com/SeleniumHQ/seleniumhq.github.io.
