### ISSUE TITLE
Incorrect Content-Encoding when downloading Selenium

### ISSUE THREAD

**Issue by straurob** [SeleniumHQ/www.seleniumhq.org#75]
Given the following URL:
http://selenium-release.storage.googleapis.com/2.53/selenium-java-2.53.0.zip

When downloading this file the `Content-Type` is correctly set. However the `Content-Encoding` is set to `None` which makes some anti-virus programs block the download. An expected value would e.g. be `pack200-gzip` or else.

**Comment by diemol** [comment]
Hi @straurob,

Apologies for the lack of response to this issue. Sadly there is no action we can take on this now, but if you still find the issue in newer versions, please raise an issue at https://github.com/seleniumhq/selenium/
