### ISSUE TITLE
had trouble finding the links to the API documentation for each language

### ISSUE THREAD

**Issue by robertpateii** [SeleniumHQ/www.seleniumhq.org#83]
Hello,

The API links for each language that are in the [selenium readme on github](https://github.com/SeleniumHQ/selenium#documentation) are not listed anywhere on the [main documentation page](http://docs.seleniumhq.org/docs/). I see now that they're in the footer in a linked called "Selenium API" but that is the last place i looked. I think the API docs are useful, but I'm not the only one who had [trouble finding them](http://stackoverflow.com/questions/5644868/webdriver-selenium-2-api-documentation).

I think it would improve findability if the API links were added to the Introduction section, the Note to Reader section, or as its own link in the doc list (even if that link jjust points to the same section on the downloads page that the ["Selenium API"](http://docs.seleniumhq.org/download/#client-drivers) link in the footer does).

In my case i'm on a project that uses selenium but another developer installed selenium. So I never saw the API links next to the download links.

Thanks,

Robert

**Comment by oren** [comment]
I have similar experience. Selenium is such a powerful tool but the website and the docs can get more love. I wonder if it's possible to apply for Google Summer of Code program - https://developers.google.com/open-source/gsoc/2016/organizations and improving the website.

**Comment by lmtierney** [comment]
All API links are also located next to their respective languages on the download page **http://docs.seleniumhq.org/download/**

**Comment by robertpateii** [comment]
@lmtierney Yeah I see them there. I'm suggesting a link to that (http://docs.seleniumhq.org/download/#client-drivers) be somewhere within the documentation section because that's the first place many people will be looking.

I'd suggest in or after the appendix:
https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/rst/index.rst

or somewhere in this section:
http://docs.seleniumhq.org/docs/03_webdriver.jsp#introducing-the-selenium-webdriver-api-by-example

Want a PR for this?

**Comment by diemol** [comment]
Hi @robertpateii,

Can you please have a look at the new [docs](https://selenium.dev/documentation/en/) and new [site](https://selenium.dev/), and in case you still find the issue, please create an issue at https://github.com/SeleniumHQ/seleniumhq.github.io.
