### ISSUE TITLE
Getting Error message while running grid version 2.53: Session was terminated due to SO_TIMEOUT Command duration or timeout: 15 milliseconds 

### ISSUE THREAD

**Issue by shishirdwivedi2008** [SeleniumHQ/www.seleniumhq.org#85]
Please help with SO_Timeout. It is coming intermittently for different different test cases.
What would be probable reason and how to fix it.

Here is logs:
Unable to take screenshot:- org.openqa.selenium.WebDriverException: Session [05fd2500-960c-4b92-b228-2594d58f30e0] was terminated due to SO_TIMEOUT Command duration or timeout: 15 milliseconds Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'XXXXXX', ip: 'XXXXXXXX', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=30.0, platform=WINDOWS, browserConnectionEnabled=true, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=05fd2500-960c-4b92-b228-2594d58f30e0, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 05fd2500-960c-4b92-b228-2594d58f30e0 at sun.reflect.GeneratedConstructorAccessor170.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:422) at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206) at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701) at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:335) at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at org.openqa.selenium.remote.Augmenter$CompoundHandler.intercept(Augmenter.java:191) at org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$20b060f4.getScreenshotAs() at Utils.Browser.captureScreenshot(Browser.java:150) at Utils.Browser.takeScreenShoot(Browser.java:1074) at Utils.Log.PageInfo(Log.java:85) at Utils.Log.Failfinal(Log.java:63) at Utils.Config.logFailureException(Config.java:659) at Utils.TestListener.onTestFailure(TestListener.java:95) at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833) at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817) at org.testng.internal.Invoker.invokeMethod(Invoker.java:758) at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882) at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189) at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124) at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) at org.testng.TestRunner.privateRun(TestRunner.java:767) at org.testng.TestRunner.run(TestRunner.java:617) at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) at org.testng.SuiteRunner.access$000(SuiteRunner.java:38) at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382) at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.openqa.grid.common.exception.GridException: Session [05fd2500-960c-4b92-b228-2594d58f30e0] was terminated due to SO_TIMEOUT at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105) at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425) at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240) at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120) at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83) at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:61) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808) at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587) at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Unknown Source) 
Unable to take screenshot:- org.openqa.selenium.WebDriverException: Session [05fd2500-960c-4b92-b228-2594d58f30e0] was terminated due to SO_TIMEOUT Command duration or timeout: 6 milliseconds Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'RahulTesting01', ip: '10.50.6.205', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=30.0, platform=WINDOWS, browserConnectionEnabled=true, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=05fd2500-960c-4b92-b228-2594d58f30e0, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 05fd2500-960c-4b92-b228-2594d58f30e0 at sun.reflect.GeneratedConstructorAccessor170.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:422) at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206) at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701) at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:326) at Utils.Browser.takeScreenShoot(Browser.java:1123) at Utils.Log.PageInfo(Log.java:85) at Utils.Log.Failfinal(Log.java:63) at Utils.Config.logFailureException(Config.java:659) at Utils.TestListener.onTestFailure(TestListener.java:95) at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833) at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817) at org.testng.internal.Invoker.invokeMethod(Invoker.java:758) at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882) at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189) at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124) at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) at org.testng.TestRunner.privateRun(TestRunner.java:767) at org.testng.TestRunner.run(TestRunner.java:617) at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) at org.testng.SuiteRunner.access$000(SuiteRunner.java:38) at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382) at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.openqa.grid.common.exception.GridException: Session [05fd2500-960c-4b92-b228-2594d58f30e0] was terminated due to SO_TIMEOUT at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105) at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425) at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240) at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120) at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83) at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:61) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808) at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587) at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Unknown Source) 
Unable to log page info:- org.openqa.selenium.WebDriverException: Session [05fd2500-960c-4b92-b228-2594d58f30e0] was terminated due to SO_TIMEOUT Command duration or timeout: 6 milliseconds Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'RahulTesting01', ip: '10.50.6.205', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_65' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=30.0, platform=WINDOWS, browserConnectionEnabled=true, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=05fd2500-960c-4b92-b228-2594d58f30e0, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 05fd2500-960c-4b92-b228-2594d58f30e0 at sun.reflect.GeneratedConstructorAccessor170.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:422) at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206) at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701) at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:326) at Utils.Browser.takeScreenShoot(Browser.java:1123) at Utils.Log.PageInfo(Log.java:85) at Utils.Log.Failfinal(Log.java:63) at Utils.Config.logFailureException(Config.java:659) at Utils.TestListener.onTestFailure(TestListener.java:95) at org.testng.internal.Invoker.runTestListeners(Invoker.java:1833) at org.testng.internal.Invoker.runTestListeners(Invoker.java:1817) at org.testng.internal.Invoker.invokeMethod(Invoker.java:758) at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882) at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189) at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124) at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) at org.testng.TestRunner.privateRun(TestRunner.java:767) at org.testng.TestRunner.run(TestRunner.java:617) at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) at org.testng.SuiteRunner.access$000(SuiteRunner.java:38) at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382) at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.openqa.grid.common.exception.GridException: Session [05fd2500-960c-4b92-b228-2594d58f30e0] was terminated due to SO_TIMEOUT at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105) at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:425) at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:240) at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:120) at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83) at org.openqa.grid.web.servlet.DriverServlet.doGet(DriverServlet.java:61) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808) at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587) at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221) at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515) at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061) at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) at org.seleniumhq.jetty9.server.Server.handle(Server.java:499) at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310) at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257) at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) at java.lang.Thread.run(Unknown Source)

**Comment by lukeis** [comment]
this is the issues list for the www.seleniumhq.org website... issues with the selenium project itself should be logged there:

https://github.com/seleniumhq/selenium
