### ISSUE TITLE
RE:argument(0).click is not a fuction in javascriptexecutor 

### ISSUE THREAD

**Issue by archanamuplams** [SeleniumHQ/www.seleniumhq.org#87]
I used javascript executor to click an element(used javascript executor because faced stale element referrence issue).When i tried to click an element using this javascript executor getting error as"argument(0).click is not a fuction".

 WebElement weekdate1 = driver.findElement(By.xpath(".//*[@id='dashboardleft']/div[2]/div/div[1]/a"));
((JavascriptExecutor) driver).executeScript("arguments[0].click();", weekdate1);

> Can you help us to overcome this issue.Thanks in advance

**Comment by manoj9788** [comment]
Hi there!

Your question is better suited for [webdriver](https://groups.google.com/forum/#!forum/webdriver) or [selenium](https://groups.google.com/forum/#!forum/selenium-users) google groups or may be in irc [selenium](http://webchat.freenode.net/?channels=selenium) channel

Please refer [selenium help](https://github.com/SeleniumHQ/selenium/wiki/Selenium-Help).

Support or debugging questions will not be answered here.

Thanks!
