### ISSUE TITLE
Timeout Exception in Webdriver.dll when running script more than once

### ISSUE THREAD

**Issue by jburkecubexsystem** [SeleniumHQ/www.seleniumhq.org#96]
INDEX FOR CONTENT IN ORDER FOUND
[Summary]
[Notes]
[Exception]
[Stack Trace]
[OS]
[Browser]
[Selenium]
[Edge Driver]
[Visual Studio]
[Script Code]

SUMMARY:
WebDriver, C#, Edge - Timeout Exception in Webdriver.dll
- Script only able to be executed once.  Subsequent attempts result in a time out exception. (stack trace shown below)
- This script opens Edge, navigates to Bing and finds an element
 
NOTES:
- Restarting the OS enables the script to be run once again.
- Similar code running in a grid configuration requires restarting the node after the script execution to enable the script to be run once again.
- Similar code using the Java language bindings and Edge works every time. No problems.

EXCEPTION:
OpenQA.Selenium.WebDriverException was unhandled
  HResult=-2146233088
  Message=The HTTP request to the remote WebDriver server for URL http://localhost:50861/session timed out after 60 seconds.
  Source=WebDriver

STACK TRACE - 
Exception thrown: 'OpenQA.Selenium.WebDriverException' in WebDriver.dll
The HTTP request to the remote WebDriver server for URL http://localhost:51410/session timed out after 60 seconds.
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor()
   at Bing.Program.Main(String[] args) in C:\Users\jburke\Documents\Visual Studio 2015\Projects\Bing\Bing\Program.cs:line 25
The request was aborted: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)

OS - 
Windows 10 Home
Version 1511
Build 10586.494
64Bit

BROWSER - 
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

SELENIUM -
package id="Selenium.Support" version="2.53.1" targetFramework="net452" 
package id="Selenium.WebDriver" version="2.53.1" targetFramework="net452"

EDGE DRIVER -
Microsoft Web Driver Version 2.0.0.0
File Version 10.0.10586.0
Product Version 10.0.10586.0

VISUAL STUDIO:
Microsoft Visual Studio Community 2015
Version 14.0.25424.00 Update 3
Microsoft .NET Framework
Version 4.6.01038

SCRIPT CODE -
https://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/

ERROR OCCURS AT LINE -> driver = new EdgeDriver();

using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Remote;

namespace EdgeDriverTests
{
    public class Program
    {
        /*
        * This assumes you have added MicrosoftWebDriver.exe to your System Path.
        * For help on adding an exe to your System Path, please see:
        * https://msdn.microsoft.com/en-us/library/office/ee537574(v=office.14).aspx
        */
        static void Main(string[] args)
        {
            RemoteWebDriver driver = null;
            try
            {
                driver = new EdgeDriver();

                // Navigate to Bing
                driver.Url = "https://www.bing.com/";

                // Find the search box and query for webdriver
                var element = driver.FindElementById("sb_form_q");

                element.SendKeys("webdriver");
                element.SendKeys(Keys.Enter);

                Console.ReadLine();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            finally
            {
                if (driver != null)
                {
                    driver.Quit();
                }
            }
        }
    }
}

**Comment by jburkecubexsystem** [comment]
I ran as admin when submitting this issue.  I have now run without elevated privileges and the script works.  Not ideal but it will do for now.

Issue also submitted with Edge and was duplicated. Issue #8252265
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8252265/

**Comment by lukeis** [comment]
this is the issues list for the www.seleniumhq.org website... issues with the selenium project itself should be logged there:

https://github.com/seleniumhq/selenium
