### ISSUE TITLE
Webdriver.close() or quit() is not closing the browser in.jar format

### ISSUE THREAD

**Issue by lamchiomeng** [SeleniumHQ/www.seleniumhq.org#97]
Webdriver ver: 2.53

Issue:
- The following three files are in the same default package. An executable jar was created for this     
   package.
   -> LoginTest_Firefox.java
   -> LoginTest_Chrome.java
   -> LoginCredentials.java
- Run the jar file created for the project.
- At the end of the execution, the browser remained and did not closed. [NG]

Note: When running this from Eclipse, the browser can be closed, regardless of using .close() or .quit()

[Issues.zip](https://github.com/SeleniumHQ/www.seleniumhq.org/files/383182/Issues.zip)

**Comment by lukeis** [comment]
please only log issues on this repository for the website www.seleniumhq.org itself.

If you have a concise reproducible test case, please log it at github.com/SeleniumHQ/selenium

From what I could see in your files you are not ensuring that quit() is called at the end of your methods, any exception earlier could cause the code to terminate earlier and thus not call driver.quit(); Selenium does not auto close the browser, you must ensure it is done. For example using something like this:

    WebDriver driver = new FirefoxDriver();
    try {
      /* your code here */
    } finally {
      driver.quit();
    }

If you have futher questions please post them to the selenium-users google group:
https://groups.google.com/forum/#!forum/selenium-users
